changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Docs
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - ci
        - dependencies
